spring:
  application:
    name: admin
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/insurance
    username: root
    password: jung8728
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090
  tomcat:
    max-http-form-post-size: 52428800
    uri-encoding: UTF-8
    use-relative-redirects: true
  #spring:
  web:
    resources:
      static-locations:
        file: ./uploads/
      chain:
        strategy:
          content:
            enabled: true

#    max-http-post-size: 10485760  # 10MB (바이트 단위)
#    max-http-form-post-size:
#logging:level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.multipart=DEBUG

