spring:
  application:
    name: admin
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/insurance
    username: root
    password: jung8728
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090
  tomcat:
    max-http-form-post-size: 52428800
    uri-encoding: UTF-8
    use-relative-redirects: true
  #spring:
  web:
    resources:
      static-locations:
        file: ./uploads/
      chain:
        strategy:
          content:
            enabled: true

#    max-http-post-size: 10485760  # 10MB (바이트 단위)
#    max-http-form-post-size:
#logging:level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.multipart=DEBUG

jwt:
  secret: rlarrkaksruemfkddldmldurtmqdlekee

aws:
  s3:
    bucket-name: "hk-project-1/meowmung-insurance/data/pdf"
    region: "ap-northeast-2"
  credentials:
    access-key: "AKIARRVGOJHT5YNF2WVD"
    secret-key: "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"